run:
  concurrency: 8
  timeout: 120s
  tests: true
linters: # Descriptions: https://github.com/golangci/awesome-go-linters
  enable-all: true
  disable:
    - wrapcheck
    - testpackage
    - tagliatelle
    - forbidigo
    - gci
    - gochecknoglobals
    - exhaustruct
    - cyclop
    - gocognit
    - nlreturn
    - maintidx
    - lll
    - paralleltest  # recomended linter in the future
    - exhaustivestruct
    - gomnd
linters-settings:
  goimports:
    local-prefixes: github.com/Iknite-Space
